name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        run: |
          docker build -t my_image_name .
          docker tag my_image_name ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:${{ github.sha }}

      - name: Update AWS ECS service
        run: |
          aws ecs update-service \
            --cluster my_cluster \
            --service my_service \
            --force-new-deployment
